const repositories = {
        oncoplotter: {
      title: "OncoPlotter",
      img: "./logo/oncoplotter.png",
      hint: "Plot Tools for Oncology Area",
      summary: "A SAS package to create figures commonly created in oncology studies.",
      license: "MIT",
      authors: ["PharmaForest"],
      maintainers: ["PharmaForest"],
      features: ["Kaplan-Meier Plot", "Swimmer Plot", "Waterfall Plot"],
      macros: ["%kaplan_meier_plot()","%swimmer_plot()","%waterfall_plot()", "%forest_plot()", "%spider_plot()"],
      badges: ["PharmaForest Original","Oncology","Output/Visualization","MIT"],
      links: [{text:"OncoPlotter", href:"https://github.com/PharmaForest/OncoPlotter"}, {navigatorKey: "askDrForest"}],
      layout: {x: 40, y: 100, scale: 0.6},
    },
    sashash: {
      title: "SAS Hash",
      img: "./logo/sashash.png",
      hint: "Hash Tools",
      summary: "Sashash package provides powerful and efficient hash-based lookup and validation tools specifically designed for SAS programming. Leveraging the robust capabilities of SAS hash objects, this package enables rapid and dynamic key-based data retrieval and existence checking directly within a single data step. This significantly reduces the need for separate sort and merge steps, streamlining workflows and enhancing performance.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["hash object"],
      macros: ["%kvlookup()","%keycheck()","%kduppchk()"],
      badges: ["hash","Data Utility","MIT"],
      links: [{text:"sashash", href:"https://github.com/PharmaForest/sashash"}, {navigatorKey: "askDrForest"}],
      layout: {x: 150, y: 100, scale: 0.6},
    },
    sas_dataset_json: {
      title: "SAS Dataset JSON",
      img: "./logo/sas_dataset_json.png",
      hint: "Dataset JSON Converter",
      summary: "Sas_dataset_json is a SAS macro package designed to support bi-directional conversion between CDISC-compliant Dataset-JSON format and SAS datasets.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Dataset JSON"],
      macros: ["%m_sas_to_json1_1()","%m_json1_1_to_sas()","%m_sas_to_ndjson1_1()","%m_ndjson1_1_to_sas()"],
      badges: ["Dataset JSON","Data Utility","MIT"],
      links: [{text:"sas_dataset_json", href:"https://github.com/PharmaForest/sas_dataset_json"}, {navigatorKey: "askDrForest"}],
      layout: {x: 260, y: 100, scale: 0.6},
    },
    saspacer: {
      title: "SASPACer",
      img: "./logo/saspacer.png",
      hint: "SAS Package Generator",
      summary: "A SAS package to help creating SAS packages. サスパッカー in the logo stands for SASPACer in Japanese. The package is to help creating SAS packages. Shaping onigiri(rice ball) by hands can be a bit challenging for beginners, but using onigiri mold makes it easy to form and provides a great introduction. Hope the mold(SASPACer) will help you to create your SAS package.",
      license: "MIT",
      authors: ["Ryo Nakaya"],
      maintainers: ["Ryo Nakaya"],
      features: ["SAS Packages"],
      macros: ["%ex2pac()","%pac2ex()"],
      badges: ["SAS Packages","Other","MIT"],
      links: [{text:"SASPACer", href:"https://github.com/PharmaForest/SASPACer"}, {navigatorKey: "askDrForest"}],
      layout: {x: 100, y: 200, scale: 0.6},
    },
    misc: {
      title: "misc",
      img: "./logo/misc.png",
      hint: "Miscellaneous Utilities",
      summary: "A SAS package to place miscellaneous macros, functions, etc..",
      license: "MIT",
      authors: ["PharmaForest"],
      maintainers: ["PharmaForest"],
      features: ["Miscellaneous Functions"],
      macros: ["%xpt2sas()","%minimize_charlen()","%roundsig()","%rounddec()","%color_swatch()",
      "swapn() routine","swapc() routine","swapn_vec() routine","swapc_vec() routine",
      "%view_swatch()", "%line_swatch()", "%symbol_swatch()", "%derive_epoch()"],
      badges: ["PharmaForest Original","Miscellaneous","Other","MIT"],
      links: [{text:"misc", href:"https://github.com/PharmaForest/misc"}, {navigatorKey: "askDrForest"}],
      layout: {x: 206, y: 200, scale: 0.6},
    },
    sas_faker: {
      title: "SAS_FAKER",
      img: "./logo/sas_faker.png",
      hint: "Dummy Data Generator",
      summary: "SAS package to create dummy data in CDISC format for clinical trials Purpose: A macro to generate dummy clinical trial data. Creates datasets in SDTM (DM, AE, SV, VS) and ADaM (ADSL, ADAE，ADVS, ADTTE) formats. Generates pseudo subject data, vital signs, study visits, and adverse events based on user-specified group numbers and sample sizes.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Dummy Data"],
      macros: ["%sas_faker()"],
      badges: ["Dummy Data","Data Utility","MIT"],
      links: [{text:"sas_faker", href:"https://github.com/PharmaForest/sas_faker"}, {navigatorKey: "askDrForest"}],
      layout: {x: 317, y: 200, scale: 0.6},
    },
    saslogchecker: {
      title: "SAS log checker",
      img: "./logo/saslogchecker.png",
      hint: "Log Checking Utility",
      summary: "SAS log checker for extracting ERRORs, WARNINGs, and notable NOTEs — supports interactive and directory-wide runs.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Log Checking"],
      macros: ["%interact_logchk()", "%logchk2directory()"],
      badges: ["Log","Checker","MIT"],
      links: [{text:"saslogchecker", href:"https://github.com/PharmaForest/saslogchecker"}, {navigatorKey: "askDrForest"}],
      layout: {x: 40, y: 295, scale: 0.6},
    },
    sas_compare: {
      title: "SAS Compare",
      img: "./logo/sas_compare.png",
      hint: "Compare Support Tools",
      summary: "Package to compare SDTM/ADaM, TLF datasets, etc. Assume a double program in the pharmaceutical industry to compare main and sub.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Compare and results checking"],
      macros: ["%ads_compare()"],
      badges: ["Compare","Checker","MIT"],
      links: [{text:"sas_compare", href:"https://github.com/PharmaForest/sas_compare"}, {navigatorKey: "askDrForest"}],
      layout: {x: 150, y: 295, scale: 0.6},
    },
    rtfcreator: {
      title: "RTF Creator",
      img: "./logo/rtfcreator.png",
      hint: "RTF Creator",
      summary: "A Package that allows you to easily create RTF files from your dataset.",
      license: "MIT",
      authors: ["Hiroki Yamanobe"],
      maintainers: ["Hiroki Yamanobe"],
      features: ["rtf tables creation"],
      macros: ["%rtfcreator()"],
      badges: ["rtf","ODSTable","Output/Visualization","MIT"],
      links: [{text:"rtfcreator", href:"https://github.com/PharmaForest/rtfcreator"}, {navigatorKey: "askDrForest"}],
      layout: {x: 260, y: 295, scale: 0.6},
    },
    shutter_chance: {
      title: "Shutter_chance",
      img: "./logo/shutter_chance.png",
      hint: "Snapshot Tools",
      summary: "SHUTTER_CHANCE: Visual Checkpoints for SAS Data Step Review. MACRO_VARIABLE_SHUTTER_CHANCE: Visually check the global and local status and values of SAS macro variables at any point.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Snapshot in Data step/Macro"],
      macros: ["%shutter_chance()", "%macro_variable_shutter_chance()"],
      badges: ["checkpoint","scope","Checker","MIT"],
      links: [{text:"shutter_chance", href:"https://github.com/PharmaForest/shutter_chance"}, {navigatorKey: "askDrForest"}],
      layout: {x: 369, y: 295, scale: 0.61},
    },
    devil: {
      title: "Developer's Ideas Library(DEVIL)",
      img: "./logo/devil.png",
      hint: "Playful Ideas for a Break",
      summary: "Welcome to Developer's Ideas Library. Share your devils (any ideas at any stage) for trial, inspiring, showing-off, recruiting members for further development by showing POC, or even joking(for fun). You can see in description.sas of devil package that author is Any Developers. Devil package is completely different from the other packages in PharmaForest with its highly collaborative nature to welcome any ideas from anyone regardless of usefulness(we would rather prefer playful ones😁). Let's take a break, knock the door of devil!",
      license: "MIT",
      authors: ["Any Developers"],
      maintainers: ["PharmaForest"],
      features: ["Collaborative and open library"],
      macros: ["%chatDMS() (Ryo Nakaya)", "text2morse() (Yutaka Morioka)", "%life_game() (Yutaka Morioka)","%sudoku_solver() (Miyuki Aso)","%hanabi() (Akira Matsuzawa, Yutaka Morioka, Ryo Nakaya)"],
      badges: ["PharmaForest Original","devil","collaborative","400 years","Other","MIT"],
      links: [{text:"devil", href:"https://github.com/PharmaForest/devil"}, {navigatorKey: "askDrForest"}],
      layout: {x: 366, y: 100, scale: 0.66},
    },
    xattr_kit: {
      title: "xattr_kit",
      img: "./logo/xattr_kit.png",
      hint: "Extended Attributes Toolkit",
      summary: "xattr_kit is a package to simplify the management of SAS extended attributes",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Extended attributes management"],
      macros: ["%xattr_set_var()", "%xattr_set_ds()", "%list_xattr()", "%xattr_in()", "%xattr2macrovar()"],
      badges: ["extended attributes","Data Utility","MIT"],
      links: [{text:"xattr_kit", href:"https://github.com/PharmaForest/xattr_kit"}, {navigatorKey: "askDrForest"}],
      layout: {x: 423, y: 205, scale: 0.63},
    },
    cloak: {
      title: "Cloak",
      img: "./logo/cloak.png",
      hint: "Check-in/Check-out Storekeeper",
      summary: "A simple FCMP-based check-in/check-out storage system using dictionary objects in SAS. Store and retrieve data by key, like a digital cloakroom.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["FCMP functions"],
      macros: ["cloak_num()", "cloak_char()", "%queue_init()", "%enqueue()", "%dequeue()", "%queue_peek()", "%stack_init()", "%stack_push()", "%stack_pop()", "%stack_peek()"],
      badges: ["check-in/check-out","Data Utility","MIT"],
      links: [{text:"cloak", href:"https://github.com/PharmaForest/cloak"}, {navigatorKey: "askDrForest"}],
      layout: {x: 530, y: 200, scale: 0.6},
    },
    vis_review_kit: {
      title: "Vis_Review_Kit",
      img: "./logo/vis_review_kit.png",
      hint: "Visual Review Toolkit",
      summary: "Visual tools for reviewing and monitoring clinical trial data. A SAS macro package to support QC and exploration through graphical representations.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Visual Review"],
      macros: ["%event_gant_excel()", "%upset_plot()"],
      badges: ["Visual review","Output/Visualization","MIT"],
      links: [{text:"vis_review_kit", href:"https://github.com/PharmaForest/vis_review_kit"}, {navigatorKey: "askDrForest"}],
      layout: {x: 470, y: 295, scale: 0.6},
    },
    odstable_layoutshowcase: {
      title: "odstable_layoutshowcase",
      img: "./logo/odstable_layoutshowcase.png",
      hint: "Showcase for ODSTable Layouts",
      summary: "A SAS macro toolkit to showcase layout patterns using PROC ODSTABLE. Provides reusable examples of table design with multi-level headers, conditional formatting, composite layouts, and auto-generated RTF output. Ideal for clinical reporting, style template development, and training use.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Showcase of odstable layout"],
      macros: ["%odstable_layoutshowcase()"],
      badges: ["ODSTable","Output/Visualization","MIT"],
      links: [{text:"odstable_layoutshowcase", href:"https://github.com/PharmaForest/odstable_layoutshowcase"}, {navigatorKey: "askDrForest"}],
      layout: {x: 473, y: 100, scale: 0.6},
    },
    maxims4sas: {
      title: "maxims4sas",
      img: "./logo/maxims4sas.png",
      hint: "Best Practices for SAS",
      summary: "This package displays maxims that have deeply impressed me and that I wish to pass on to future generations.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Output maxims for SAS programmers"],
      macros: ["%sas_maxims()"],
      badges: ["maxims","Other","MIT"],
      links: [{text:"maxims4sas", href:"https://github.com/PharmaForest/maxims4sas"}, {navigatorKey: "askDrForest"}],
      layout: {x: 94, y: 390, scale: 0.6},
    },
    laglead: {
      title: "LAGLEAD",
      img: "./logo/laglead.png",
      hint: "Dynamic lead/lag value access",
      summary: "SAS utilities for dynamic lead/lag value access.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["lead", "lag"],
      macros: ["%laglead()"],
      badges: ["lag","lead","Data Utility","MIT"],
      links: [{text:"laglead", href:"https://github.com/PharmaForest/laglead"}, {navigatorKey: "askDrForest"}],
      layout: {x: 205, y: 390, scale: 0.6},
    },
    ctcae5_grader: {
      title: "CTCAE5_grader",
      img: "./logo/ctcae5_grader.png",
      hint: "CTCAE Grader",
      summary: "ctcae5_grader is a SAS macro package that automates the grading of laboratory tests according to CTCAE v5.0. It standardises grading rules for common laboratory parameters (e.g. haematology, biochemistry, electrolytes) and provides character and numeric grade outputs.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["CTCAE", "Grading"],
      macros: ["%CTCAE_XXX() [e.g. %CTCAE_ALT()]"],
      badges: ["CTCAE","grading","Data Utility","MIT"],
      links: [{text:"ctcae5_grader", href:"https://github.com/PharmaForest/ctcae5_grader"}, {navigatorKey: "askDrForest"}],
      layout: {x: 315, y: 389, scale: 0.6},
    },
    love_matrix: {
      title: "Love_Matrix",
      img: "./logo/love_matrix.png",
      hint: "Loving matrix via FCMP",
      summary: "Love_Matrix is a SAS macro toolkit for basic matrix operations (multiply, inverse, determinant, Cholesky, etc.) — works with PROC FCMP, no SAS/IML required.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["matrix", "operations"],
      macros: ["%matrix_mult()", "%matrix_inverse()", "%matrix_identity()", "%matrix_determinant()", "%matrix_transpose()", "%matrix_cholesky_decomposition()"],
      badges: ["matrix","love","Data Utility","MIT"],
      links: [{text:"love_matrix", href:"https://github.com/PharmaForest/love_matrix"}, {navigatorKey: "askDrForest"}],
      layout: {x: 422, y: 390, scale: 0.56},
    },
    SASPACerShiny: {
      title: "SASPACerShiny",
      img: "./logo/SASPACerShiny.png",
      hint: "Shiny App of SASPACer",
      summary: "サスパッカー in the logo stands for SASPACer in Japanese. Original SASPACer is a SAS package to support creating SAS packages. SASPACer Shiny is an R shiny application with the same purpose. By providing GUI interface, SASPACer Shiny supports R users to create SAS packages. Once SAS package source folder/file structure is done by SASPACer Shiny, users should run %generatePackage() in SAS Package Framework(SPF) using SAS to complete creating SAS packages. By the way, original SASPACer is suite tool until completion of creating SAS packages.",
      license: "MIT",
      authors: ["Ryo Nakaya"],
      maintainers: ["Ryo Nakaya"],
      features: ["SAS Packages"],
      macros: ["Not Applicable (SASPACerShiny::run_app())"],
      badges: ["SAS Packages","R", "Shiny", "Other","MIT"],
      links: [{text:"SASPACerShiny", href:"https://github.com/PharmaForest/SASPACerShiny"}, {navigatorKey: "askDrForest"}],
      layout: {x: 530, y: 390, scale: 0.6},
    },
    change_tracer_dog: {
      title: "Change Tracer Dog",
      img: "./logo/change_tracer_dog.png",
      hint: "Change Tracer Macros",
      summary: "Change Tracer Dog is a SAS macro package that behaves like a police dog: tracing dataset changes, sniffing out differences, and stopping patrol when the mission is complete.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Tracing dataset changes"],
      macros: ["%dog_patrol()", "%sniffer_compare()", "%patrol_end()", "%dog_chatter()"],
      badges: ["tracer","datasets", "change", "dog", "Checker","MIT"],
      links: [{text:"change_tracer_dog", href:"https://github.com/PharmaForest/change_tracer_dog"}, {navigatorKey: "askDrForest"}],
      layout: {x: 40, y: 482, scale: 0.61},
    },
    yaml_writer: {
      title: "YAML Writer",
      img: "./logo/yaml_writer.png",
      hint: "YAML Generation Tool",
      summary: "A lightweight SAS macro package to generate YAML files directly from SAS. It lets you: - Start and end YAML output streams, - Export datasets into YAML (mapping, sequence, mappingsequence), - Build nested or inline structures. Write YAML directly between %yaml_start and %yaml_end, use &nw. for line breaks, and %dataset_export / %nest / %inline_nest for structured output.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["writing YAML"],
      macros: ["%yaml_start()", "%yaml_end()", "%dataset_export()", "%nest()", "%inline_nest()"],
      badges: ["yaml", "Other","MIT"],
      links: [{text:"yaml_writer", href:"https://github.com/PharmaForest/yaml_writer"}, {navigatorKey: "askDrForest"}],
      layout: {x: 150, y: 482, scale: 0.6},
    },
    adamski: {
      title: "Adamski",
      img: "./logo/adamski.png",
      hint: "Adam Creation Tool",
      summary: "The adamski package is currently under development to support ADaM creation. Let's build the spaceship [adamski] together! 🛰️ Inspired by the admiral package in R, adamski aims to bring similar functionality — along with original functions and macros — to the SAS environment. We are looking for collaborators and contributors to join us on this exciting journey. If you’re passionate about ADaM programming or want to help shape tools for the clinical data community, we’d love to have you onboard! 🚀",
      license: "Apache-2.0",
      authors: ["PharmaForest"],
      maintainers: ["PharmaForest"],
      features: ["creating CDISC ADaM"],
      macros: ["%derive_vars_dy()", "%derive_var_merged_exist_flag()", "%derive_var_age_years()", "%derive_locf_records()", "%derive_var_base()", "%derive_var_chg()", "%derive_var_obs_number()", "%derive_vars_aage()", "%derive_vars_joined()"],
      badges: ["ADaM", "Data Utility","Apache-2.0"],
      links: [{text:"Adamski", href:"https://github.com/PharmaForest/adamski"}, {navigatorKey: "askDrForest"}],
      layout: {x: 260, y: 482, scale: 0.6},
    },
    RWDExpress: {
      title: "RWDExpress",
      img: "./logo/RWDExpress.png",
      hint: "RWD handling toolkit",
      summary: "RWD Express — a SAS package designed to accelerate your Real World Data journey. It helps you prepare your SAS environment for efficient RWD processing. Provides practical tools to handle, clean, and organize large, complex datasets.",
      license: "MIT",
      authors: ["Narusawa-T"],
      maintainers: ["Narusawa-T"],
      features: ["Handling RWD(big data)"],
      macros: ["%index_single_key()", "%small_world()", "%split_world()"],
      badges: ["RWD", "Big Data", "Data Utility","MIT"],
      links: [{text:"RWDExpress", href:"https://github.com/PharmaForest/RWDExpress"}, {navigatorKey: "askDrForest"}],
      layout: {x: 370, y: 483, scale: 0.62},
    },
    freqsum: {
      title: "freqsum",
      img: "./logo/freqsum.png",
      hint: "Frequency and Summary Tool",
      summary: "This package allows you to easily perform frequency tabulations and summary statistics.",
      license: "MIT",
      authors: ["Hiroki Yamanobe"],
      maintainers: ["Hiroki Yamanobe"],
      features: ["Frequency tabulations", "Summary statistics"],
      macros: ["%freqStat()", "%summaryStat()"],
      badges: ["Frequency","Summary","Output/Visualization","MIT"],
      links: [{text:"freqsum", href:"https://github.com/PharmaForest/freqsum"}, {navigatorKey: "askDrForest"}],
      layout: {x: 475, y: 482, scale: 0.6},
    },
    qc_cat_referee: {
      title: "QC_Cat_Referee",
      img: "./logo/qc_cat_referee.png",
      hint: "toolkit for automated data quality control",
      summary: "A SAS macro toolkit for automated data quality control. Applies integrity constraints to judge datasets (OK/NG) and outputs clear, visual QC results — with a cat referee making the call.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["QC", "Integrity constraints"],
      macros: ["%cat_rule_judgment()", "%cat_unique_judgment()", "%cat_unique_not_missing_judgment()"],
      badges: ["QC","Constraints","Checker","MIT"],
      links: [{text:"qc_cat_referee", href:"https://github.com/PharmaForest/qc_cat_referee"}, {navigatorKey: "askDrForest"}],
      layout: {x: 96, y: 579, scale: 0.6},
    },
    SASToolbox: {
      title: "SASToolbox",
      img: "./logo/SASToolbox.png",
      hint: "Toolbox to handle files all at once",
      summary: "A SAS macros tool box which contains utility macros to handle files, datasets, and codes all at once.",
      license: "MIT",
      authors: ["Shingo Suzuki"],
      maintainers: ["Shingo Suzuki"],
      features: ["Tools", "handling all at once"],
      macros: ["%trancd2u8_d()", "%Read_csv_in_folder()", "%Read_excel_in_folder()", "%includeAll()"],
      badges: ["encoding","files","Data Utility","MIT"],
      links: [{text:"SASToolbox", href:"https://github.com/PharmaForest/SASToolbox"}, {navigatorKey: "askDrForest"}],
      layout: {x: 206, y: 581, scale: 0.59},
    },
    trial_flow: {
      title: "trial_flow",
      img: "./logo/trial_flow.png",
      hint: "Macros to create flow diagrams",
      summary: "A SAS macro package for creating flow diagrams, including CONSORT diagrams, with boxes, lines, and plots for clinical trial workflows.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["trial flow", "diagrams"],
      macros: ["%diagram_box()", "%diagram_line()", "%diagram_plot()"],
      badges: ["trial flow diagrams","Output/Visualization","MIT"],
      links: [{text:"trial_flow", href:"https://github.com/PharmaForest/trial_flow"}, {navigatorKey: "askDrForest"}],
      layout: {x: 315, y: 579, scale: 0.64},
    },
    valivali: {
      title: "valivali",
      img: "./logo/valivali.png",
      hint: "Toolbox for validation",
      summary: "Valivali is a validation toolbox that provides utilities to test and validate SAS packages. Use it during package creation and verification to ensure expected behavior and reproducible results. Valivali loads {sasjscore} package developed by Allan Bowe when valivali is loaded and strongly influenced and powered by sasjscore. You need to install {sasjscore} to use the package. By loading valivali, users can utilize valivali original macros in addition to {sasjscore} macros for validation. BTW, `valivali` means bad boy's vibes in Japanese😁",
      license: "MIT",
      authors: ["PharmaForest"],
      maintainers: ["PharmaForest"],
      features: ["validation", "assertion"],
      macros: ["%mp_assertdataset()", "%mp_assertgraph()", "other macros in {sasjscore}", "%set_tmp_lib()", "%create_report()"],
      badges: ["validation","Checker","MIT"],
      links: [{text:"valivali", href:"https://github.com/PharmaForest/valivali"}, {navigatorKey: "askDrForest"}],
      layout: {x: 423, y: 579, scale: 0.6},
    },
    mergex: {
      title: "mergex",
      img: "./logo/mergex.png",
      hint: "Merge methods for non-standard situations",
      summary: "MERGEX is a package that enables non-standard or unconventional joins not easily handled or supported by standard SAS syntax. It currently implements variable-name conflict-safe joins, and will support rolling joins and other advanced join types in future releases.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["merge", "non-standard joins"],
      macros: ["%varconf_merge()", "%rolling_match()"],
      badges: ["merge/join","Data Utility","MIT"],
      links: [{text:"mergex", href:"https://github.com/PharmaForest/mergex"}, {navigatorKey: "askDrForest"}],
      layout: {x: 530, y: 579, scale: 0.64},
    },
    basketMiningKit: {
      title: "basketMiningKit",
      img: "./logo/basketMiningKit.png",
      hint: "Package for Association analysis",
      summary: "BasketMiningKit is a package that Perform association analysis using only Base SAS functionality, without using Enterprise Miner or SAS Viya.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Association analysis"],
      macros: ["%association_rule_mining()"],
      badges: ["Association analysis","Output/Visualization","MIT"],
      links: [{text:"basketMiningKit", href:"https://github.com/PharmaForest/basketMiningKit"}, {navigatorKey: "askDrForest"}],
      layout: {x: 40, y: 672, scale: 0.63},
    },
    datacut_sas: {
      title: "datacut_sas",
      img: "./logo/datacut_sas.png",
      hint: "Data Cutting Tool",
      summary: "Datacut_SAS is a set of SAS macros to prepare SDTM for data-cut analyses: remove post-cutoff records, overwrite with the cutoff date/time, drop subjects, and null flags. Supports multiple cutoff operations and generates an Excel report summarizing all applied changes.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Data-cut"],
      macros: ["%cutoff_setting()", "%cutoff_overwrite()", "%cutoff_delete()", "%cutoff_missing()", "%delete_participants()", "%output_and_report()"],
      badges: ["Data-cut","SDTM","raw data","Data Utility","MIT"],
      links: [{text:"datacut_sas", href:"https://github.com/PharmaForest/datacut_sas"}, {navigatorKey: "askDrForest"}],
      layout: {x: 150, y: 672, scale: 0.6},
    },
    retro_spell_check: {
      title: "retro_spell_check",
      img: "./logo/retro_spell_check.png",
      hint: "Batch Spell Verifier",
      summary: "Batch spell verification for all files in a target folder. For each file, runs PROC SPELL with optional custom dictionary, writes the spell output to a per-file .txt, aggregates results, and exports a review-friendly Excel report.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Spell Check"],
      macros: ["%retro_spell_check()"],
      badges: ["Spell check","Batch","Checker","MIT"],
      links: [{text:"retro_spell_check", href:"https://github.com/PharmaForest/retro_spell_check"}, {navigatorKey: "askDrForest"}],
      layout: {x: 260, y: 672, scale: 0.64},
    },
    sas_dataset_toon: {
      title: "sas_dataset_toon",
      img: "./logo/sas_dataset_toon.png",
      hint: "Toon generator",
      summary: "This package contains SAS macros for converting between SAS datasets and TOON (Token-Oriented Object Notation) format. This repository is an adapted version of Saikrishnareddy Yengannagari’s original package (https://github.com/kusy2009/sas_dataset_toon) tailored for the SAS Package Framework, and the original license remains the property of Saikrishnareddy Yengannagari.",
      license: "MIT",
      authors: ["Saikrishnareddy Yengannagari"],
      maintainers: ["Saikrishnareddy Yengannagari","Yutaka Morioka"],
      features: ["TOON generation"],
      macros: ["%sas2toon()", "%toon2sas()"],
      badges: ["TOON","Converter","Data Utility","MIT"],
      links: [{text:"sas_dataset_toon", href:"https://github.com/PharmaForest/sas_dataset_toon"}, {navigatorKey: "askDrForest"}],
      layout: {x: 370, y: 672, scale: 0.6},
    },
    defensivechk: {
      title: "defensivechk",
      img: "./logo/defensivechk.png",
      hint: "Defensive checks macros",
      summary: "This repository contains a SAS macro designed to perform defensive checks on macro parameters, datasets, and variables. It ensures that the necessary items are defined before further data processing, and if any required items are missing or incorrect, it will provide error messages and can abort execution. This repository is an adapted version of Saikrishnareddy Yengannagari’s original package (https://github.com/kusy2009/defensivechk) tailored for the SAS Package Framework, and the original license remains the property of Saikrishnareddy Yengannagari.",
      license: "MIT",
      authors: ["Saikrishnareddy Yengannagari"],
      maintainers: ["Saikrishnareddy Yengannagari","Yutaka Morioka"],
      features: ["defensive checks"],
      macros: ["%defensivechk()"],
      badges: ["Defensive Checks","macro","Checker","MIT"],
      links: [{text:"defensivechk", href:"https://github.com/PharmaForest/defensivechk"}, {navigatorKey: "askDrForest"}],
      layout: {x: 476, y: 672, scale: 0.63},
    },
    GetCDISCCodelist: {
      title: "GetCDISCCodelist",
      img: "./logo/GetCDISCCodelist.png",
      hint: "Get CDISC Codelist",
      summary: "This SAS macro retrieves and filters CDISC Controlled Terminology (CT) codelists for various CDISC standards (SDTM, ADaM, CDASH, etc.). The macro interacts with the CDISC Terminology API to fetch the latest terminology version and filters the codelists based on the specified input parameters. This repository is an adapted version of Saikrishnareddy Yengannagari’s original package (https://github.com/kusy2009/getCDISCCOdelist) tailored for the SAS Package Framework, and the original license remains the property of Saikrishnareddy Yengannagari.",
      license: "MIT",
      authors: ["Saikrishnareddy Yengannagari"],
      maintainers: ["Saikrishnareddy Yengannagari","Yutaka Morioka"],
      features: ["CDISC", "Codelists"],
      macros: ["%GetCDISCCodelist()"],
      badges: ["CDISC","Codelists","fetch","Other","MIT"],
      links: [{text:"GetCDISCCodelist", href:"https://github.com/PharmaForest/GetCDISCCodelist"}, {navigatorKey: "askDrForest"}],
      layout: {x: 96, y: 762, scale: 0.6},
    },
    kpi_viz_toolbox: {
      title: "kpi_viz_toolbox",
      img: "./logo/kpi_viz_toolbox.png",
      hint: "KPI Visualization Toolbox",
      summary: "KPI visualization macros for tracking and reporting SDTM/ADaM/TLF programming progress, including counts and proportion-based indicators for delivery status.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["KPI Visualization"],
      macros: ["%number_kpi()", "%proportion_kpi()"],
      badges: ["KPI","proc GKPI","Output/Visualization","MIT"],
      links: [{text:"kpi_viz_toolbox", href:"https://github.com/PharmaForest/kpi_viz_toolbox"}, {navigatorKey: "askDrForest"}],
      layout: {x: 207, y: 763, scale: 0.6},
    },
    outlier_screening: {
      title: "outlier_screening",
      img: "./logo/outlier_screening.png",
      hint: "Outlier screening tools",
      summary: "outlier_screening is a SAS macro toolkit for fast, review-friendly outlier detection. It flags extremes using SD (Z-score), MAD (robust Z), and IQR rules, adds ranks, and generates an annotated boxscatter plot for quick data screening.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Outlier Detection"],
      macros: ["%outlier_sd()", "%outlier_mad()", "%outlier_iqr()", "%outlier_all3()"],
      badges: ["Outlier","Screening","Checker","MIT"],
      links: [{text:"outlier_screening", href:"https://github.com/PharmaForest/outlier_screening"}, {navigatorKey: "askDrForest"}],
      layout: {x: 316, y: 761, scale: 0.59},
    },
    sARDen: {
      title: "sARDen",
      img: "./logo/sARDen.png",
      hint: "ARD Developer",
      summary: "sARDen is a SAS toolkit for producing CDISC ARS–aligned Analysis Results Data (ARD). Inspired by the R pharmaverse cards schema, it respectfully mirrors ARD conventions for cross-language workflows. Macros cover summaries, tabulations, and hierarchical stacking, outputting long-format ARDs plus ARDM-like metadata via XATTR for traceability.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["ARD Creation"],
      macros: ["%sard_summary()", "%sard_tabulate()", "%sard_stack_hierarchical()", "%sard_stack_hierarchical_count()", "%bind_ard()", "%xrdm_set()"],
      badges: ["ARD","Analysis Results Data","Data Utility","MIT"],
      links: [{text:"sARDen", href:"https://github.com/PharmaForest/sARDen"}, {navigatorKey: "askDrForest"}],
      layout: {x: 40, y: 851, scale: 0.6},
    },
    sARDenX: {
      title: "sARDenX",
      img: "./logo/sARDenX.png",
      hint: "Extended ARD Developer",
      summary: "sARDenX is an extension of sARDen, aiming to generate CDISC ARD (Analysis Results Data) from a wide range of SAS statistical analysis procedures.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Extended ARD Creation"],
      macros: ["%sard_stats_t_test()", "%sard_stats_fisher_test()"],
      badges: ["ARD","Analysis Results Data","Data Utility","MIT"],
      links: [{text:"sARDenX", href:"https://github.com/PharmaForest/sARDenX"}, {navigatorKey: "askDrForest"}],
      layout: {x: 150, y: 851, scale: 0.6},
    },
    sARDenMTS: {
      title: "sARDenMTS",
      img: "./logo/sARDenMTS.png",
      hint: "ARD Metadata Manager",
      summary: "A SAS-native authoring framework for CDISC Analysis Results Metadata Technical Specification (ARM-TS). Users define ARS-compliant study, analysis, and output metadata via simple SAS macros that append to normalized metadata tables. The package validates key constraints and exports a hierarchical YAML ARM-TS file using yaml_writer. Designed to integrate seamlessly with sARDen (ARD builder), with the longer-term goal of fully metadata-driven, reproducible TLF production. This integration layer is currently under active development.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["ARD Metadata"],
      macros: ["%ars_init()", "%ars_write_yaml()", "%ars_add_study()", "%ars_add_dataset()", "%ars_add_variable()", "%ars_add_statistic()", "%ars_add_layout()", "%ars_add_meta()", "%ars_add_model()", "%ars_add_estimand()", "%ars_add_contrast()", "%ars_add_multiplicity()", "%ars_add_group()", "%ars_add_layout()"],
      badges: ["ARD","Analysis Results Data","Metadata","Data Utility","MIT"],
      links: [{text:"sARDenMTS", href:"https://github.com/PharmaForest/sARDenMTS"}, {navigatorKey: "askDrForest"}],
      layout: {x: 260, y: 851, scale: 0.6},
    },
    corr: {
      title: "corr",
      img: "./logo/corr.png",
      hint: "Association Analysis Tools",
      summary: "A SAS package to provide macros for computing association measures between continuous, nominal, and ordinal variables. This package supports Pearson and Spearman correlations, Cramer's V, Somers' D, and Eta coefficient. Macro in the package outputs both long-format association tables and wide matrix-style datasets for further analysis. Includes a heatmap macro to visualize the strength and type of associations in a single plot. Tools for analysis or visualization related to correlation and association are to be added.",
      license: "MIT",
      authors: ["Ryo Nakaya"],
      maintainers: ["Ryo Nakaya"],
      features: ["Association analysis"],
      macros: ["%association_matrix()", "%heatmap()", "%scatter_matrix()"],
      badges: ["Association","Correlation","Output/Visualization","MIT"],
      links: [{text:"corr", href:"https://github.com/PharmaForest/corr"}, {navigatorKey: "askDrForest"}],
      layout: {x: 423, y: 761, scale: 0.64},
    },
    sas2typst_report: {
      title: "sas2typst_report",
      img: "./logo/sas2typst_report.png",
      hint: "Typst Report Generator",
      summary: "sas2typst_report is a SAS macro package that enables direct generation of Typst (.typ) files from within SAS. Typst is a modern, declarative typesetting system designed for fast and precise document layout. This package allows users to write native Typst code inline in SAS programs and seamlessly stream SAS dataset contents into Typst tables.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["Typst Report Generation"],
      macros: ["%typst_start()", "%typst_end()", "%typ_dataset_csv()"],
      badges: ["typst","report","Output/Visualization","MIT"],
      links: [{text:"sas2typst_report", href:"https://github.com/PharmaForest/sas2typst_report"}, {navigatorKey: "askDrForest"}],
      layout: {x: 531, y: 764, scale: 0.62},
    },
    dataset_maker: {
      title: "dataset_maker",
      img: "./logo/dataset_maker.png",
      hint: "Dataset Maker",
      summary: "The dataset_maker package is intended to consolidate functions related to generating SAS datasets. As its first feature, the ds2datalines macro converts a SAS dataset back into dataset creation code.",
      license: "MIT",
      authors: ["Yutaka Morioka"],
      maintainers: ["Yutaka Morioka"],
      features: ["SAS datasets generation"],
      macros: ["%ds2datalines()"],
      badges: ["dataset","generator","Data Utility","MIT"],
      links: [{text:"dataset_maker", href:"https://github.com/PharmaForest/dataset_maker"}, {navigatorKey: "askDrForest"}],
      layout: {x: 370, y: 854, scale: 0.6},
    },  
    sashighlight: {
      title: "SAShighlight",
      img: "./logo/SAShighlight.png",
      hint: "Visually Highlight Tool",
      summary: "SAS Highlight is a utility package designed to visually highlight data points, subjects, or groups that meet specific conditions in ODS Graphics plots. The package focuses on commonly used exploratory and review graphics in clinical and analytical workflows, especially: - Spaghetti plots - Scatter plots",
      license: "MIT",
      authors: ["Yoshiki Tokuda"],
      maintainers: ["Yoshiki Tokuda"],
      features: ["Highlighting in ODS Graphics"],
      macros: ["%fig_setup()", "%highlight_attrmap()", "%highlight_refline()", "%highlight_spaghetti()", "%highlight_series()", "%highlight_scatter_by_individual()", "%highlight_scatter_by_group()"],
      badges: ["ODS Graphics","Highlight","Output/Visualization","MIT"],
      links: [{text:"sashighlight", href:"https://github.com/PharmaForest/sashighlight"}, {navigatorKey: "askDrForest"}],
      layout: {x: 476, y: 854, scale: 0.62},
    },   
    sasdogs: {
      title: "SASDoGs",
      img: "./logo/SASDoGs.png",
      hint: "SAS Documentation Generator system",
      summary: "SAS Documentation Generator system - Generate document from SAS code with JupyterBook/Sphinx support and GitHub Pages automation",
      license: "MIT",
      authors: ["Ken Nakamatsu"],
      maintainers: ["Ken Nakamatsu"],
      features: ["Documentation generation for SAS code"],
      macros: ["%collectFiles()", "%generateMD()", "%packageDoc()"],
      badges: ["Documentation","Package","Other","MIT"],
      links: [{text:"sasdogs", href:"https://github.com/PharmaForest/SASDoGs"}, {navigatorKey: "askDrForest"}],
      layout: {x: 96, y: 942, scale: 0.6},
    }
}

// Next layouts to be added:
//   layout: {x:  96, y: 942, scale: 0.6},
//   layout: {x: 206, y: 942, scale: 0.6},
//   layout: {x: 316, y: 942, scale: 0.6},
//   layout: {x: 426, y: 942, scale: 0.6},
//   layout: {x: 536, y: 942, scale: 0.6},

//   layout: {x:  40, y: 1037, scale: 0.6},
//   layout: {x: 150, y: 1037, scale: 0.6},
//   layout: {x: 260, y: 1037, scale: 0.6},
//   layout: {x: 370, y: 1037, scale: 0.6},
//   layout: {x: 480, y: 1037, scale: 0.6},